"""
xg_engine.py
============
Fetches xG data from Understat for all five leagues and builds
rolling team-level xG features that can be merged into code_1 and code_2.

What Understat gives us per match:
  - home_xG  : total xG generated by the home side
  - away_xG  : total xG generated by the away side
  - (implicit) xGA = the opponent's xG

Why this matters vs SOT:
  SOT counts every shot equally. A tap-in and a 35-yard screamer
  both count as 1. xG weights each shot by its actual probability
  of going in based on location, angle, body part, assist type, etc.
  Rolling xG is a far stronger signal of true attacking/defensive quality.

Features produced per team (rolling EMA, span=6, shifted to avoid leakage):
  - xg_for_ema    : rolling avg xG created
  - xg_against_ema: rolling avg xG conceded
  - xg_diff_ema   : xg_for - xg_against (net dominance)
  - xg_ratio_ema  : xg_for / (xg_for + xg_against + 0.1)  [0-1 scale]

Understat league name map (these are the exact strings the API expects):
  E0  -> EPL
  SP1 -> La_Liga
  D1  -> Bundesliga
  I1  -> Serie_A
  F1  -> Ligue_1

Seasons available: 2014/15 onwards (season arg = start year, e.g. 2024 = 2024/25)
"""

import pandas as pd
import numpy as np
import time
import warnings
warnings.filterwarnings('ignore')

# Understat league name map — matches your existing LEAGUE_CONFIG keys
UNDERSTAT_LEAGUE_MAP = {
    'E0':  'EPL',
    'SP1': 'La_Liga',
    'D1':  'Bundesliga',
    'I1':  'Serie_A',
    'F1':  'Ligue_1',
}

# Seasons to pull: 2014/15 through current 2025/26
# Understat uses the start year (2014 = 2014/15 season)
UNDERSTAT_SEASONS = [str(y) for y in range(2014, 2026)]


def fetch_xg_data(league_code: str) -> pd.DataFrame:
    """
    Pulls all available Understat match data for a given league_code
    (e.g. 'E0', 'SP1') across all seasons.

    Returns a DataFrame with columns:
        date, home_team, away_team, home_xg, away_xg

    Returns empty DataFrame on failure — callers must handle this gracefully.
    """
    understat_name = UNDERSTAT_LEAGUE_MAP.get(league_code)
    if not understat_name:
        print(f"xG Engine: Unknown league code {league_code}")
        return pd.DataFrame()

    try:
        from understatapi import UnderstatClient
    except ImportError:
        print("xG Engine: understatapi not installed — pip install understatapi")
        return pd.DataFrame()

    all_matches = []

    print(f"xG Engine: Fetching Understat data for {understat_name}...")

    with UnderstatClient() as understat:
        for season in UNDERSTAT_SEASONS:
            try:
                matches = understat.league(league=understat_name).get_match_data(season=season)
                for m in matches:
                    # Only include completed matches (isResult = True)
                    if not m.get('isResult', False):
                        continue
                    all_matches.append({
                        'date':      m['datetime'][:10],   # YYYY-MM-DD
                        'home_team': m['h']['title'],
                        'away_team': m['a']['title'],
                        'home_xg':   float(m['xG']['h'] or 0),
                        'away_xg':   float(m['xG']['a'] or 0),
                    })
                # Be polite — small delay between season requests
                time.sleep(0.5)
            except Exception as e:
                # Season may not exist yet — not an error
                print(f"  xG Engine: {understat_name} {season} skipped ({e})")
                continue

    if not all_matches:
        print(f"xG Engine: No data retrieved for {league_code}")
        return pd.DataFrame()

    df = pd.DataFrame(all_matches)
    df['date'] = pd.to_datetime(df['date'])
    df = df.sort_values('date').reset_index(drop=True)
    print(f"xG Engine: {league_code} — {len(df)} matches loaded.")
    return df


def build_rolling_xg_features(xg_df: pd.DataFrame, ewm_span: int = 6) -> pd.DataFrame:
    """
    Takes the raw match-level xG DataFrame and builds rolling EMA features
    per team. Uses shift(1) to ensure only past data informs each prediction
    (no data leakage).

    Returns a DataFrame indexed by (date, team) with columns:
        xg_for_ema, xg_against_ema, xg_diff_ema, xg_ratio_ema
    """
    if xg_df.empty:
        return pd.DataFrame()

    # Reshape to long format: one row per team per match
    home = xg_df[['date', 'home_team', 'home_xg', 'away_xg']].copy()
    home.columns = ['date', 'team', 'xg_for', 'xg_against']

    away = xg_df[['date', 'away_team', 'away_xg', 'home_xg']].copy()
    away.columns = ['date', 'team', 'xg_for', 'xg_against']

    stream = pd.concat([home, away]).sort_values(['team', 'date']).reset_index(drop=True)

    # Rolling EMA — shift(1) so each row only sees PAST games
    grouped = stream.groupby('team')

    stream['xg_for_ema']     = grouped['xg_for'].transform(
        lambda x: x.shift(1).ewm(span=ewm_span, adjust=False).mean()
    )
    stream['xg_against_ema'] = grouped['xg_against'].transform(
        lambda x: x.shift(1).ewm(span=ewm_span, adjust=False).mean()
    )

    # Fill NaN (first few matches) with league averages
    avg_for     = stream['xg_for'].mean()
    avg_against = stream['xg_against'].mean()
    stream['xg_for_ema']     = stream['xg_for_ema'].fillna(avg_for)
    stream['xg_against_ema'] = stream['xg_against_ema'].fillna(avg_against)

    # Derived features
    stream['xg_diff_ema']  = stream['xg_for_ema'] - stream['xg_against_ema']
    stream['xg_ratio_ema'] = stream['xg_for_ema'] / (
        stream['xg_for_ema'] + stream['xg_against_ema'] + 0.1
    )

    return stream[['date', 'team', 'xg_for_ema', 'xg_against_ema', 'xg_diff_ema', 'xg_ratio_ema']]


def merge_xg_into_match_df(match_df: pd.DataFrame, xg_features: pd.DataFrame) -> pd.DataFrame:
    """
    Merges rolling xG features into the main match DataFrame.
    match_df must have columns: date, home_team, away_team
    xg_features comes from build_rolling_xg_features()

    Adds columns:
        H_xg_for_ema, H_xg_against_ema, H_xg_diff_ema, H_xg_ratio_ema
        A_xg_for_ema, A_xg_against_ema, A_xg_diff_ema, A_xg_ratio_ema
        Diff_xg_diff   (home net xG dominance minus away net xG dominance)
        Diff_xg_ratio  (home xG ratio minus away xG ratio)
    """
    if xg_features.empty:
        # Return original df with zero-filled xG columns so rest of pipeline
        # continues to work without crashing
        for prefix in ['H_', 'A_']:
            for col in ['xg_for_ema', 'xg_against_ema', 'xg_diff_ema', 'xg_ratio_ema']:
                match_df[f'{prefix}{col}'] = 0.0
        match_df['Diff_xg_diff']  = 0.0
        match_df['Diff_xg_ratio'] = 0.0
        return match_df

    feat_cols = ['xg_for_ema', 'xg_against_ema', 'xg_diff_ema', 'xg_ratio_ema']

    # Home side
    home_feat = xg_features.rename(columns={
        'team': 'home_team',
        **{c: f'H_{c}' for c in feat_cols}
    })
    match_df = match_df.merge(
        home_feat[['date', 'home_team'] + [f'H_{c}' for c in feat_cols]],
        on=['date', 'home_team'], how='left'
    )

    # Away side
    away_feat = xg_features.rename(columns={
        'team': 'away_team',
        **{c: f'A_{c}' for c in feat_cols}
    })
    match_df = match_df.merge(
        away_feat[['date', 'away_team'] + [f'A_{c}' for c in feat_cols]],
        on=['date', 'away_team'], how='left'
    )

    # Fill any unmatched rows with league averages from xg_features
    for prefix, cols_prefix in [('H_', 'xg_for_ema'), ('A_', 'xg_for_ema')]:
        for col in feat_cols:
            full_col = f'{prefix}{col}'
            if full_col not in match_df.columns:
                match_df[full_col] = 0.0
            else:
                fallback = xg_features[col].mean() if col in xg_features.columns else 0.0
                match_df[full_col] = match_df[full_col].fillna(fallback)

    # Final differential features (the ones the models actually use)
    match_df['Diff_xg_diff']  = match_df['H_xg_diff_ema']  - match_df['A_xg_diff_ema']
    match_df['Diff_xg_ratio'] = match_df['H_xg_ratio_ema'] - match_df['A_xg_ratio_ema']

    return match_df


def get_current_xg_stats(team: str, xg_features: pd.DataFrame) -> dict:
    """
    Returns the most recent rolling xG stats for a given team.
    Used at prediction time (not training time).

    Returns dict with keys: xg_for_ema, xg_against_ema, xg_diff_ema, xg_ratio_ema
    Falls back to neutral values if team not found.
    """
    fallback = {
        'xg_for_ema':     1.35,  # League average xG per game approx
        'xg_against_ema': 1.35,
        'xg_diff_ema':    0.0,
        'xg_ratio_ema':   0.5,
    }

    if xg_features.empty:
        return fallback

    team_rows = xg_features[xg_features['team'] == team]
    if team_rows.empty:
        return fallback

    last = team_rows.iloc[-1]
    return {
        'xg_for_ema':     float(last['xg_for_ema']),
        'xg_against_ema': float(last['xg_against_ema']),
        'xg_diff_ema':    float(last['xg_diff_ema']),
        'xg_ratio_ema':   float(last['xg_ratio_ema']),
    }
